# CPS847 Group 11 A2 - kjhgsdxdfsdsdfsdffssdfjhg
sudo: required
language: python
python:
  - "3.7"
install: "pip install -r requirements.txt"

services:
- docker

script:
- coverage run unittest_api.py
- docker image build -t taskdummy123/cps847-a2 .

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to Docker hub
  - docker push taskdummy123/cps847-a2
  # - docker push cathyliudev/cps847-a2-docker:latest
  # code coverage testasdasd
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  app: "cps847-a2"
  env: "Cps847a2-env"
  bucket_name: "elasticbeanstalk-us-east-2-493246452076"
  on:
    branch: main

